<a href="https://colab.research.google.com/github/Infant-Joshva/Data-Science-learning-path/blob/main/Project_4(Multiple_Disease_Prediction)/notebooks/Kidney_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset-2 (Kidney Disease Prediction) - Data Preprocessing

#### Importing Necessary Packages for Data Cleaning

In [1]:
import pandas as pd

In [2]:
sheet_id= '1cew2eJA_0YRwYC5BOZdSl8fhTY0hSOVtD0xRfhevlgI'
sheet_name = "sheet1"

#https://docs.google.com/spreadsheets/d/1cew2eJA_0YRwYC5BOZdSl8fhTY0hSOVtD0xRfhevlgI/edit?usp=drivesdk

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

kidney_df=pd.read_csv(url)

In [10]:
kidney_df.head(10)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,...,39.0,7800.0,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,...,36.0,NaN,NaN,no,no,no,good,no,no,ckd
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,...,44.0,6900.0,5.0,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,...,33.0,9600.0,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29.0,12100.0,3.7,yes,yes,no,poor,no,yes,ckd

In [3]:
kidney_df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

####Deleting Duplicate Values

In [41]:
kidney_df.duplicated().sum()

np.int64(0)

In [42]:
kidney_df.drop_duplicates(inplace=True)

####Handling Null Values

In [43]:
(4/400)*100

1.0

In [37]:
kidney_df.isna().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                71
wc                106
rc                131
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [45]:
kidney_df.groupby('age')['bp'].mean()

age
2.0      NaN
3.0      NaN
4.0      NaN
5.0     50.0
6.0     60.0
        ...
80.0    72.5
81.0    60.0
82.0    80.0
83.0    70.0
90.0    90.0
Name: bp, Length: 76, dtype: float64

In [49]:
kidney_df[kidney_df['bp'].isna()]

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,...,44.0,6900.0,5.0,no,yes,no,good,yes,no,ckd
75,75,5.0,NaN,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,no,yes,ckd
132,132,50.0,NaN,NaN,NaN,NaN,normal,NaN,notpresent,notpresent,...,24.0,13200.0,2.7,yes,no,no,good,yes,yes,ckd
138,138,73.0,NaN,1.010,1.0,0.0,NaN,NaN,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,no,no,ckd
161,161,62.0,NaN,1.015,3.0,0.0,abnormal,NaN,notpresent,notpresent,...,42.0,10200.0,4.8,yes,yes,no,good,no,no,ckd
164,164,14.0,NaN,1.015,0.0,0.0,NaN,NaN,notpresent,notpresent,...,40.0,9500.0,5.4,no,yes,no,poor,yes,no,ckd
185,185,4.0,NaN,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,34.0,NaN,NaN,no,no,no,good,no,no,ckd
187,187,3.0,NaN,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,34.0,12300.0,NaN,no,no,no,good,no,no,ckd
188,188,8.0,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,...,38.0,NaN,NaN,no,no,no,good,no,no,ckd
215,215,2.0,NaN,1.010,3.0,0.0,normal,abnormal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
293,293,50.0,NaN,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,48.0,4700.0,5.4,no,no,no,good,no,no,notckd
316,316,35.0,NaN,1.020,0.0,0.0,normal,normal,NaN,NaN,...,48.0,5000.0,5.2,no,no,no,good,no,no,notckd

####Data Type conversion

In [9]:
kidney_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             329 non-null    float64
 17  wc              294 non-null    float64
 18  rc              269 non-null    float64
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(14), int64(1), object(11)
memory usage: 81.4+ KB

In [31]:
kidney_df['classification'].unique()

array(['ckd', 'notckd'], dtype=object)

Need to change Data types for this column *"float"* to *"int"*
1. Age - Int
2. BP - Int
3. AL - Int
4. Su - Int
5. gr - Int
6. bu - Int
7. pcv - Int
8. wc - Int

In [32]:
kidney_df['age'] = kidney_df['age'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
https://docs.google.com/spreadsheets/d/1cew2eJA_0YRwYC5BOZdSl8fhTY0hSOVtD0xRfhevlgI/edit?usp=drivesdk