<a href="https://colab.research.google.com/github/Infant-Joshva/Data-Science-learning-path/blob/main/Mini_Project_1(Secure_check)Git/Mini_project_1(Secure_Check).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini Project(Secure Check) Initialation and Data Cleaning

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
sheet_id= '16qEUKckLFy7j1qoSd1bSQURn9QXDb6ffSBAWzRkPsSg'
sheet_name = "sheet1"

#https://docs.google.com/spreadsheets/d/16qEUKckLFy7j1qoSd1bSQURn9QXDb6ffSBAWzRkPsSg/edit?gid=1282651194#gid=1282651194

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

traffic_df=pd.read_csv(url)

<ipython-input-4-3468746139>:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  traffic_df=pd.read_csv(url)

In [13]:
traffic_df.head(10)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
5,2020-01-01,0:05:00,Canada,F,44,73,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,2020-01-01,0:06:00,USA,F,80,70,White,Signal Violation,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
7,2020-01-01,0:07:00,India,M,72,50,Asian,Drunk Driving,Other,False,NaN,Arrest,True,30+ Min,True,DL75KZ7835
8,2020-01-01,0:08:00,USA,F,80,30,Hispanic,Other,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
9,2020-01-01,0:09:00,USA,M,43,21,Asian,Signal Violation,Signal,True,NaN,Warning,True,16-30 Min,False,KA79RD2271

####Data Type conversion

In [8]:
traffic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](1), int64(2), object(10)
memory usage: 6.7+ MB

In [7]:
traffic_df['stop_date']=pd.to_datetime(traffic_df['stop_date'])

In [11]:
traffic_df['stop_time'] = pd.to_datetime(traffic_df['stop_time'], format='%H:%M:%S').dt.time

0        00:00:00
1        00:01:00
2        00:02:00
3        00:03:00
4        00:04:00
           ...
65533    12:13:00
65534    12:14:00
65535    12:15:00
65536    12:16:00
65537    12:17:00
Name: stop_time, Length: 65538, dtype: object

####Handling Null Values

In [30]:
traffic_df.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [29]:
traffic_df['search_type'].value_counts(dropna=False)

search_type
Frisk             21971
Vehicle Search    21847
None              21720
Name: count, dtype: int64

In [19]:
traffic_df.head(10)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
5,2020-01-01,0:05:00,Canada,F,44,73,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,2020-01-01,0:06:00,USA,F,80,70,White,Signal Violation,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
7,2020-01-01,0:07:00,India,M,72,50,Asian,Drunk Driving,Other,False,NaN,Arrest,True,30+ Min,True,DL75KZ7835
8,2020-01-01,0:08:00,USA,F,80,30,Hispanic,Other,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
9,2020-01-01,0:09:00,USA,M,43,21,Asian,Signal Violation,Signal,True,NaN,Warning,True,16-30 Min,False,KA79RD2271

In [24]:
traffic_df.loc[traffic_df['search_type'].isna(),'search_type']='None' #Replace Nan to None

In [32]:
traffic_df['country_name'].value_counts()

country_name
India     21998
Canada    21908
USA       21632
Name: count, dtype: int64

In [33]:
traffic_df['driver_gender'].value_counts()

driver_gender
F    32881
M    32657
Name: count, dtype: int64

In [35]:
traffic_df['driver_age_raw'].value_counts()

driver_age_raw
75    1134
50    1100
41    1089
40    1083
59    1080
      ...
44     987
65     986
78     986
25     981
47     980
Name: count, Length: 63, dtype: int64

In [36]:
traffic_df['driver_race'].value_counts()

driver_race
White       13168
Black       13131
Other       13122
Asian       13111
Hispanic    13006
Name: count, dtype: int64

In [37]:
traffic_df['violation_raw'].value_counts()

violation_raw
Seatbelt            13204
Speeding            13148
Signal Violation    13113
Drunk Driving       13094
Other               12979
Name: count, dtype: int64

In [38]:
traffic_df['violation'].value_counts()

violation
Other       13194
Speeding    13150
Signal      13112
DUI         13075
Seatbelt    13007
Name: count, dtype: int64

In [39]:
traffic_df['search_conducted'].value_counts()

search_conducted
False    32837
True     32701
Name: count, dtype: int64

In [40]:
traffic_df['search_type'].value_counts()

search_type
Frisk             21971
Vehicle Search    21847
None              21720
Name: count, dtype: int64

In [41]:
traffic_df['stop_outcome'].value_counts()

stop_outcome
Warning    21966
Ticket     21838
Arrest     21734
Name: count, dtype: int64

In [42]:
traffic_df['is_arrested'].value_counts()

is_arrested
True     32846
False    32692
Name: count, dtype: int64

In [43]:
traffic_df['stop_duration'].value_counts()

stop_duration
30+ Min      21958
0-15 Min     21831
16-30 Min    21749
Name: count, dtype: int64

In [44]:
traffic_df['drugs_related_stop'].value_counts()

drugs_related_stop
True     32769
False    32769
Name: count, dtype: int64

In [45]:
traffic_df['vehicle_number'].value_counts()

vehicle_number
UP89PT2924    1
UP76DY3473    1
MH42PF3736    1
UP10NB3599    1
GJ34FX6230    1
             ..
KA40AD3153    1
MH89ZF7676    1
WB63BB8305    1
RJ76TI3807    1
RJ32OM7264    1
Name: count, Length: 65538, dtype: int64

####Deleting Unwanted Row

In [51]:
traffic_df.drop(['driver_age'], axis=1, inplace=True)  # if you only use cleaned age

In [52]:
traffic_df.head(10)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
5,2020-01-01,0:05:00,Canada,F,44,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,2020-01-01,0:06:00,USA,F,80,White,Signal Violation,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
7,2020-01-01,0:07:00,India,M,72,Asian,Drunk Driving,Other,False,None,Arrest,True,30+ Min,True,DL75KZ7835
8,2020-01-01,0:08:00,USA,F,80,Hispanic,Other,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
9,2020-01-01,0:09:00,USA,M,43,Asian,Signal Violation,Signal,True,None,Warning,True,16-30 Min,False,KA79RD2271

####Deleting Duplicate Values

In [48]:
traffic_df.drop_duplicates(inplace=True) #Used to drop the duplicate values

In [50]:
traffic_df.duplicated().sum()

np.int64(0)

####Storing Cleaned Data to SQL

In [54]:
from sqlalchemy import create_engine, inspect
engine=create_engine(db_url) # Importing necessary packages from pandas

In [55]:
db_url="postgresql://infant:5kV8T4PGM0C3pHexclSBZU80ijwqBMxn@dpg-d0mmus3e5dus738lfkgg-a.singapore-postgres.render.com/traffic" #Database Connection, Host Name, Password, Database Name

In [56]:
traffic_df.to_sql('traffic_stop',engine,index=False,if_exists='replace') # Creating New Table and storing the cleaned data into SQL

538

In [61]:
query = """SELECT * FROM traffic_stop"""

filtered_df = pd.read_sql(query,engine)
filtered_df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,Black,Seatbelt,Other,False,None,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,Other,Seatbelt,Speeding,True,None,Ticket,True,16-30 Min,False,UP89PT2924

In [62]:
traffic_df.to_csv('cleaned_traffic_stop.csv', index=False)